# Generated by Django 5.0.4 on 2026-02-25 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('duties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dutyinstance',
            name='assigned_soldiers',
            field=models.ManyToManyField(blank=True, related_name='duties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dutyinstance',
            name='duty_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duties.dutytype'),
        ),
    ]
