# Generated by Django 5.0.4 on 2026-02-25 11:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('duties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rule_type', models.CharField(choices=[('max_duties_per_month', 'Max duties per month'), ('avoid_consecutive_days', 'Avoid consecutive days'), ('weekend_rotation', 'Weekend rotation')], max_length=64)),
                ('value', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReplacementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('duty_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_requests', to='duties.dutyinstance')),
            ],
        ),
    ]
