# Generated by Django 5.0.4 on 2026-02-25 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='replacementrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_replacements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='replacementrequest',
            name='requested_replacement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_requests_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='replacementrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_replacements', to=settings.AUTH_USER_MODEL),
        ),
    ]
