# Generated by Django 5.0.4 on 2026-04-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0003_scheduletemplate"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="scheduletemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(is_default=True),
                fields=("is_default",),
                name="unique_default_schedule_template",
            ),
        ),
    ]
